### ISSUE TITLE
Prefer dark theme per OS setting

### ISSUE THREAD

**Issue by paul-griffith** [paul-griffith/kindling#14]
https://github.com/Dansoftowner/jSystemThemeDetector
https://bugs.openjdk.java.net/browse/JDK-8235460

Probably not worth caring about.

**Comment by Joshlha** [comment]
I have minimal knowledge of kotlin and swing (I learned JavaFX in school, go figure) but I got this working on startup, just didn't add a listener. If this is ample I'll create a pull request.

**Comment by paul-griffith** [comment]
Yeah, if you want to throw a PR up, I'd be happy to take a look. I think one-time detection would be fine.
