### ISSUE TITLE
Windows (and Mac?) Right-click to open option

### ISSUE THREAD

**Issue by Joshlha** [paul-griffith/kindling#46]
This would definitely save a few clicks and make the overall process easier.

See reference image, a feature similar to VS Code, Skype, ShareX etc:
![image](https://user-images.githubusercontent.com/43594988/157508724-39346c5b-3bb4-43f3-9651-2681e7ea7469.png)

**Comment by paul-griffith** [comment]
Adding shell integration would require diving into registry editing, which I don't _want_ to do...
https://www.howtogeek.com/howto/windows-vista/add-any-application-to-the-desktop-right-click-menu-in-vista/

You should be able to set Kindling as the 'Open With' application and it will 'do the right thing' when set up that way.
