### ISSUE TITLE
List open Java processes and add ability to capture thread dumps

### ISSUE THREAD

**Issue by paul-griffith** [paul-griffith/kindling#50]
https://github.com/JetBrains/intellij-community/blob/0e2aa4030ee763c9b0c828f0b5119f4cdcc66f35/java/debugger/impl/src/com/intellij/debugger/impl/attach/JavaAttachDebuggerProvider.java
https://github.com/JetBrains/intellij-community/blob/0e2aa4030ee763c9b0c828f0b5119f4cdcc66f35/java/debugger/impl/src/com/intellij/debugger/impl/attach/PidRemoteConnection.java
https://docs.oracle.com/en/java/javase/11/docs/api/jdk.attach/com/sun/tools/attach/spi/package-summary.html
https://docs.oracle.com/en/java/javase/11/docs/api/jdk.attach/com/sun/tools/attach/VirtualMachine.html

**Comment by Joshlha** [comment]
I don't know if this is possible. The only thing I could find as part of the attach API (which is what jstack uses) is package protected and can't be accessed.

I think we could use the gwcmd utility to take a thread dump on newer versions. Maybe I'm missing something.

**Comment by paul-griffith** [comment]
Yeah, I was excited when I made this issue, but some further exploration didn't really pan out. May still be possible in some way, so I'll leave this open.
