### ISSUE TITLE
Click to edit idb table Values

### ISSUE THREAD

**Issue by Joshlha** [paul-griffith/kindling#53]
A DB Query Browser-like functionality where double-clicking a string/int field will allow editing, or boolean checkboxes can be clicked to toggle. Then, a button to apply changes will run the queries.

This would really only work with tables that have a primary key as with the query browser in the designer.

**Comment by paul-griffith** [comment]
This would require some larger scale refactoring; right now all sqlite connections are read-only. Also, e.g. the gwbk explorer extracts to a temp directory; if edits are allowed it needs to be able to zip back up once edits are done.

It's a fun idea though, for sure.

**Comment by paul-griffith** [comment]
https://github.com/inductiveautomation/kindling/issues/15
