### ISSUE TITLE
Better UX around selecting a cache file/DB

### ISSUE THREAD

**Issue by paul-griffith** [paul-griffith/kindling#6]
Currently, you provide a .zip file and it's inspected to hopefully find a single directory that is an HSQL database.
This is pretty limited. 
For one, it would be good to support passing a direct path to a cache file.
For another, .zip files come in many forms, and even in testing I found that sometimes there would be a `folder/` explicit entry, and sometimes where wouldn't be. Perhaps after choosing your zip, it should be exploded and a dialog presented where you confirm the correct entry is contained (or are allowed to abort cleanly).

**Comment by Joshlha** [comment]
@paul-griffith Anything else need to be done on this front? I feel like zips are handled nicely now, and the cache viewer can open based on hsql files.

**Comment by paul-griffith** [comment]
No, agreed, this is pretty good now
