### ISSUE TITLE
Double click/context menu to go from a thread to its blocker(s)

### ISSUE THREAD

**Issue by paul-griffith** [paul-griffith/kindling#62]
If a single blocker, double click should directly jump to that ID (regardless of sort)
If multiple blockers, right click (or double click?) should open a context menu with the blocker IDs and allow easy jumps to the blocking threads

**Comment by Joshlha** [comment]
Single-blocker is implemented in multi-thread view comparison pane.

**Comment by Joshlha** [comment]
I think this issue can be closed now right?
