### ISSUE TITLE
Machine-readable exports

### ISSUE THREAD

**Issue by paul-griffith** [paul-griffith/kindling#8]
For known/parseable data types, we should have useable export in a format like XML, JSON or even just CSV. This _won't_ be an attempt to match the existing quarantine import/export format, but a totally new format.

**Comment by paul-griffith** [comment]
Revive if demand shows up.

**Comment by paul-griffith** [comment]
Demand showed up.

**Comment by njminchin** [comment]
Hello, this is Demand speaking! xD

**Comment by Joshlha** [comment]
@njminchin What do think would be most useful to export currently? Threads, logs, database, etc? It'll be useful to know what we should implement first.

**Comment by paul-griffith** [comment]
Excel and CSV exports are available for thread dumps since #55; will be live in the next published release
